export const movies = [
  {
    id: 5926,
    title: "feshin on TV",
    muvie_url: "http//sdvs6dv/sfsvsv",
    genre: "crime",
    release_date: "05/04/2022",
    year: "2022",
    ruting: 85,
    runtime: "test run time",
    overview: "overview to long ",
  },
  {
    id: 26,
    title: "Mask on face",
    muvie_url: "http//sdvs6dv/sfsvsv",
    genre: "horror",
    release_date: "08/08/1989",
    year: "1989",
    ruting: 85,
    runtime: "test run time",
    overview: "overview to long ",
  },
  {
    id: 263,
    title: "Smash",
    muvie_url: "https://www.v/ssfsfsvsv",
    genre: "comedy",
    release_date: "01/08/2009",
    year: "2009",
    ruting: 85,
    runtime: "test run time",
    overview: "overview to long ",
  },

  {
    id: 2863,
    title: "Good time",
    muvie_url: "https://www.v/ssfsfsvsv",
    genre: "comedy",
    release_date: "28/08/2009",
    year: "2009",
    ruting: 85,
    runtime: "test run time",
    overview: "overview tosfsfsfs long ",
  },
  
];
